application: motivationization
version: demo
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /images
  static_dir: images

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  login: required
  script: main.app

- url: /_ah/login_required
  script: do_openid_login.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
